if (process.env.NODE_ENV !== "production") {
  require("dotenv").config();
}

module.exports = {
	SECURITY_SRC_0_NAME: process.env.SECURITY_SRC_0_NAME,
	SECURITY_SRC_1_NAME: process.env.SECURITY_SRC_1_NAME,
	SECURITY_SRC_2_NAME: process.env.SECURITY_SRC_2_NAME,
	SECURITY_SRC_3_NAME: process.env.SECURITY_SRC_3_NAME,
	SECURITY_SRC_4_NAME: process.env.SECURITY_SRC_4_NAME,
	SECURITY_SECRET_KEY_SRC_1: process.env.SECURITY_SECRET_KEY_SRC_1,
	SECURITY_SECRET_KEY_SRC_2: process.env.SECURITY_SECRET_KEY_SRC_2,
	SECURITY_SECRET_KEY_SRC_3: process.env.SECURITY_SECRET_KEY_SRC_3,
	SECURITY_SECRET_KEY_SRC_4: process.env.SECURITY_SECRET_KEY_SRC_4,
	SECURITY_ALGORITHM_SRC_1: process.env.SECURITY_ALGORITHM_SRC_1,
	SECRET_HMAC_KEY:  process.env.SECRET_HMAC_KEY, // CR0016 
};
